### ISSUE TITLE
Support custom Sponsorable users 

### ISSUE THREAD

**Issue by dansiegel** [JasonEtco/is-sponsor-label-action#12]
# Description

Some Projects are not sponsorable as an organization, but the individual maintainers are. It doesn't seem there is currently a way to customize which account the action should check for. 

For example you can look at the [PrismLibrary](/PrismLibrary/Prism). This is a GitHub organizational account which isn't directly sponsorable. However both Brian and I are. I would love to be able to use this for Prism so that when anyone opens an issue or PR it could be labeled with the sponsor label if they sponsor either Brian or myself.

**Comment by IvanGodinez21** [comment]
Same problem, I hope this added soon. It would be nice to include the sponsors from the repository instead of the repository owner

**Comment by dansiegel** [comment]
@IvanGodinez21 you might want to check out the [sponsor-action](https://github.com/brianlagunas/sponsor-action) by @brianlagunas... we use that for PrismLib
