### ISSUE TITLE
Organization Support

### ISSUE THREAD

**Issue by fatihyildizhan** [JasonEtco/is-sponsor-label-action#4]
Hi, this is a lovely action.

Is it possible to adopt this to Organizations?

We have a public-repository on this Organization and have sponsors too. We would like to use this action on Organization repositories.

This lists the sponsors
`{
  organization(login: "doxa-labs") {
    sponsorshipsAsMaintainer(first: 100) {
      nodes {
        sponsor {
          id
        }
      }
    }
  }
}`

Sample organization:
https://github.com/doxa-labs

Also, which personal access token scopes are needed to add sponsor-label?

Thank you

**Comment by JasonEtco** [comment]
Hello! Thanks for the issue @fatihyildizhan. I added support for org-owned repos in #5 🎉 

> Also, which personal access token scopes are needed to add sponsor-label?

Just the default token that is provided by GitHub Actions will suffice!
