### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by fatihyildizhan** [JasonEtco/is-sponsor-label-action#41]
Hi, it gives 'Resource not accessible by integration' and GitHub Action fails. Can you please suggest us a solution? Thanks a lot.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/602600/226535429-0df56cd1-e1b2-4c77-9e19-d119f0317de9.png">

**Comment by JasonEtco** [comment]
Duplicate of #28
