### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by fatihyildizhan** [JasonEtco/is-sponsor-label-action#6]
Action throws a **Validation Failure** with _already_exists_ message when the second issue opens.

![first](https://user-images.githubusercontent.com/602600/76068718-bab53580-5fa2-11ea-8f4c-5130c3cf62df.png)

https://github.com/doxa-labs/ExcelLabs/runs/489751634?check_suite_focus=true

![already-exists](https://user-images.githubusercontent.com/602600/76068666-9d806700-5fa2-11ea-8e76-171dfc3a1f6f.png)

**Comment by JasonEtco** [comment]
Thanks for the report @fatihyildizhan! I opened up #7 to fix this. I assumed that the `try/catch` here would ignore this error, but apparently not:

https://github.com/JasonEtco/is-sponsor-label-action/blob/25fc2b7152a7413b4ee36adb6a1653fc7fa3baa4/lib/create-label.js#L10-L16
